apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-ingressgateway
    istio: example-ingressgateway
  name: example-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    port: 15020
    targetPort: 15020
  - name: http2
    nodePort: 30380
    port: 80
    targetPort: 80
  - name: https
    nodePort: 30390
    port: 443
  - name: tcp
    nodePort: 30400
    port: 31400
  - name: https-kiali
    port: 15029
    targetPort: 15029
  - name: https-prometheus
    port: 15030
    targetPort: 15030
  - name: https-grafana
    port: 15031
    targetPort: 15031
  - name: https-tracing
    port: 15032
    targetPort: 15032
  - name: tls
    port: 15443
    targetPort: 15443
  selector:
    app: example-ingressgateway
    istio: example-ingressgateway
  type: LoadBalancer
