apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hello-v2-cert
  namespace: istio-system
spec:
  secretName: istio-example-ingressgateway-certs
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: hello-v2.35.222.172.208.xip.io
  dnsNames:
  - hello-v2.35.222.172.208.xip.io
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - hello-v2.35.222.172.208.xip.io