apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hello-v1-cert
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: hello-v1.35.202.120.220.xip.io
  dnsNames:
  - hello-v1.35.202.120.220.xip.io
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - hello-v1.35.202.120.220.xip.io